spring.application.name=consumer-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:55432/consumer
spring.datasource.username=workflow
spring.datasource.password=workflow

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

app.aws.region=us-east-1
app.sqs.endpoint=http://localhost:4566
app.sqs.queue-name=document-approved
app.consumer.poll-interval-ms=1000
