spring.application.name=workflow-service

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info

app.sqs.enabled=false
app.aws.region=us-east-1
app.sqs.queue-name=document-approved
app.sqs.dlq-name=document-approved-dlq
app.outbox.relay.interval-ms=2000
